# Generated by Django 5.1 on 2024-08-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nombre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
