# Generated by Django 4.1.7 on 2023-02-21 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
